#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/bspwm"
RASI="$DIR/rofi/windows.rasi"

# Run
rofi \
    -show window \
	-theme ${RASI}
