#!/usr/bin/env bash


##################################################
# RDBHVR - 2026
##################################################

# bspwm directory
DIR="$HOME/.config/bspwm"

# rofi sudo askpass helper
export SUDO_ASKPASS="$DIR"/scripts/rofi_askpass

# execute the application
sudo -A $1
