#!/usr/bin/env bash


##################################################
# RDBHVR - 2026
##################################################

# bspwm directory
DIR="$HOME/.config/bspwm"

# fix padding
bspc config bottom_padding 0
bspc config top_padding 0

# launch polybar
bash "$DIR"/polybar/launch.sh
