#!/usr/bin/env bash


##################################################
# RDBHVR - 2026
##################################################

# bspwm directory
DIR="$HOME/.config/bspwm"

# Launch dunst daemon
if [[ `pidof dunst` ]]; then
	pkill dunst
fi

dunst -config "$DIR"/dunstrc &
